using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ChestInteract : MonoBehaviour
{
    public KeyCode openKey = KeyCode.E;
    public float interactDistance = 1.5f;

    Animator anim;
    bool opened = false;
    bool rewardGiven = false;
    Transform player;

    public Item rewardItem;
    public int rewardCount = 1;

    // КИЛѓ ОЦРЬХл

    void Awake()
    {
        anim = GetComponent<Animator>();

        var go = GameObject.FindGameObjectWithTag("Player");
        if (go) player = go.transform;
    }

    void Update()
    {
        if (opened) return;
        if (!player) return;

        if (Input.GetKeyDown(openKey) && InRange())
        {
            Open();
        }
    }

    void Open()
    {
        opened = true;

        if (anim != null)
            anim.SetTrigger("Open");
        else
            GiveReward();
    }

    bool InRange()
    {
        float sqr = ((Vector2)player.position - (Vector2)transform.position).sqrMagnitude;
        return sqr <= interactDistance * interactDistance;
    }

    public void GiveReward()
    {
        if (rewardGiven) return;
        rewardGiven = true;

        if (rewardItem == null || rewardCount <= 0) return;

        if (Inventory.instance == null)
        {
            Debug.LogWarning("[ChestInteract] Inventory.instanceАЁ ОјНРДЯДй!");
            return;
        }

        bool ok = Inventory.instance.AddItem(rewardItem, rewardCount);

        if (!ok)
        {
            Debug.Log("[ChestInteract] РЮКЅРЬ АЁЕц ТїМ­ КИЛѓ СіБо НЧЦа! (ЛѓРк ДйНУ П­ Мі РжАд ЕЧЕЙИВ)");
            opened = false;
            rewardGiven = false;
        }
    }

    }
