using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SeasonTilemapController : MonoBehaviour
{
    [Header("Seasonal Tilemaps For This Scene")]
    public GameObject springTilemap;
    public GameObject summerTilemap;
    public GameObject fallTilemap;
    public GameObject winterTilemap;

    void OnEnable()
    {
        if (SeasonManager.Instance != null)
        {
            // ОРРЬ ФбСњ ЖЇ, ЧіРч АшР§ПЁ ИТАд Чб Йј РћПы
            ApplySeason(SeasonManager.Instance.currentSeason);
            // РЬШФ АшР§ КЏАц РЬКЅЦЎ БИЕЖ
            SeasonManager.Instance.OnSeasonChanged += ApplySeason;
        }
    }

    void OnDisable()
    {
        if (SeasonManager.Instance != null)
        {
            SeasonManager.Instance.OnSeasonChanged -= ApplySeason;
        }
    }
    void ApplySeason(Season season)
    {
        if (springTilemap) springTilemap.SetActive(season == Season.Spring);
        if (summerTilemap) summerTilemap.SetActive(season == Season.Summer);
        if (fallTilemap) fallTilemap.SetActive(season == Season.Fall);
        if (winterTilemap) winterTilemap.SetActive(season == Season.Winter);
    }
}
